# Generated by Django 4.2.1 on 2024-01-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='numer_phone',
            new_name='number_phone',
        ),
    ]
