# Generated by Django 5.0.1 on 2024-01-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_grade_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default='default_image.jpg', upload_to='product_images/'),
        ),
    ]
