# Generated by Django 5.0.1 on 2024-02-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderitem_deliveryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='buy',
            field=models.BooleanField(default=False),
        ),
    ]
