# Generated by Django 5.0.1 on 2024-02-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderitem_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfo',
            name='house_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='street',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='method_pay',
            field=models.CharField(choices=[('przełew na konto', 'przełew na konto'), ('oplata za pobraniem', 'oplata za pobraniem'), ('BLIK', 'BLIK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='shipping_method',
            field=models.CharField(choices=[('DHL', 'DHL'), ('Poczta polska', 'Poczta polska'), ('Fedex', 'Fedex'), ('Odbior w sklepie', 'Odbior w sklepie')], max_length=255),
        ),
    ]
